name: Python application

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install SDL dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsmpeg-dev libportmidi-dev libfreetype6-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame
        pip install pytest

    - name: Run the solver
      run: |
        python solver.py

    - name: Run tests
      run: |
        pytest tests/
